[workspace]
resolver = "2"
members = ["day*", "utils/*"]

[workspace.dependencies]
itertools = "0.12.0"
rayon = "1.8.0"
grid = "0.13.0"
arrayvec = "0.7.4"
num = "0.4.1"
pathfinding = "4.6.0"
indicatif = "0.17.7"
criterion = { version = "0.5.1", features = ["html_reports"] }
